export const RoutePath = {
  LandingPage: "/",
  About: "/about",
  PrivacyPolicy: "/privacy-policy",
  ReturnPolicy: "/return-policy",
  TermsAndConditions: "/terms-and-conditions",
  Login: "/login",
  Waitlist: "/waitlist",
  Home: "/home",
  Products: "/products",
  ProductPage: "/product",
  DashboardHome: "/dashboard/home",
  DashboardAdminAndBranch: "/dashboard/admin-branch",
  DashboarBudget: "/dashboard/budget",
  DashboardReport: "/dashboard/report",
  DashboardInvoice: "/dashboard/invoice",
  DashboardRaiseQuery: "/dashboard/raise-query",
};
